### ISSUE TITLE
option not in drop down

### ISSUE THREAD

**Issue by Geezus42** [timrogers/obsidian-share-as-gist#104]
Obsidian version: 0.15.9

Just installed the plugin, enabled, added PAT and it does not show up in the command drop down.

**Comment by timrogers** [comment]
Can you try turning the plugin on and off again, and restart Obsidian? I've not heard of this issue before, so just want to cover the obvious bases.

**Comment by Geezus42** [comment]
Turned it off, restarted obsidian, turned it back on, now the option is their. Thank you.
