### ISSUE TITLE
Time-based sync to gist

### ISSUE THREAD

**Issue by Jamalam360** [timrogers/obsidian-share-as-gist#397]
Forgive me if I'm wrong, but I believe you are not able to keep a Gist in sync with an Obsidian document as it is edited (obviously it wouldn't be live, it would do it every X minutes or when the document is closed). Could this feature be added?

**Comment by timrogers** [comment]
You're right - the extension doesn't support that at the moment. I'm not sure that I'll have time to add it, but I'm certainly open to a pull request.
