### ISSUE TITLE
Feature request: Disable frontmatter inclusion 

### ISSUE THREAD

**Issue by masonc15** [timrogers/obsidian-share-as-gist#44]
Hello,

I love this addon, but don't have a need for the big block of gist-related frontmatter that appears when using it. If there could be an option to disable that, that would be incredible. Thank you!

**Comment by timrogers** [comment]
To be fair, I can probably implement that a different way that doesn’t use messy front-matter 😊

**Comment by masonc15** [comment]
Hi,

Thanks for the response!  I quickly just create a gist once and share it, similarly to Pastebin or something.  While I understand how editing the existing gist could be useful, it's not one of my use cases.  If it's a hassle to add this functionality, don't worry about it!  It's a bit of a nit-pick anyway :)  Thanks!

**Comment by timrogers** [comment]
This is fixed in v1.1.0, which I've just released. You can turn off the "Enable updating gists after creation" option - which is disabled by default - to stop this from happening.
