### ISSUE TITLE
Blank lines included at the beginning of the note after private sharing

### ISSUE THREAD

**Issue by jmbenedetto** [timrogers/obsidian-share-as-gist#602]
Hello. Thanks a lot for the amazing plugin.

Action:
Share a note using the option "Share as private gist on GitHub.com".

Expected result:
Get the note replicated as a private gist.
No change to the Obsidian note (Enable updating gists afet creation => False)

Actual result:
Get the note replicated as a private gist.
3 empty lines added to Obsidian note (Enable updating gists afet creation => False)

Impact:
Obsidian properties no longer rendered correctly.

This does not happen when sharing as public gist.

<img width="705" alt="Screenshot 2024-07-11 at 14 39 43" src="https://github.com/timrogers/obsidian-share-as-gist/assets/28365534/64acca09-3d4f-4724-a0da-664d05e0e117">
<img width="199" alt="Screenshot 2024-07-11 at 14 32 27" src="https://github.com/timrogers/obsidian-share-as-gist/assets/28365534/ed7415df-0489-4cba-8e4b-b9e632e75a0b">
<img width="450" alt="Screenshot 2024-07-11 at 14 31 51" src="https://github.com/timrogers/obsidian-share-as-gist/assets/28365534/7e2b1195-dfad-4a8f-b211-918247f9a9b9">

**Comment by timrogers** [comment]
Do you see the same issue if you use the "Create gist" button in the "Set a description for your gist" box, rather than hitting the Return key?

**Comment by timrogers** [comment]
If I am correct about the problem, I think I have a fix in https://github.com/timrogers/obsidian-share-as-gist/pull/603 😊 It fixes the extra lines for me!
